### ISSUE TITLE
Define what is a good name

### ISSUE THREAD

**Issue by wencanluo** [wencanluo/good-bad-names-for-GN#15]

**Comment by dimus** [comment]
I think we have two levels of 'ideal goodness' and at this stage we are solving only first level.

### 1: Names valid according to nomenclature, 'objective names'.

Such names are:
- valid according to a corresponding code (zoological ICZN, botanical ICN, cultivar ICNCP etc)
- have a desciption according to the code rules
- have or had valid type specimen in a museum/collection
- have a reference (a traditional paper, or electronic for newly registered names)

They are 'objective' because they have a fact -- a nomenclatural act attached to them. Even if these names are considered 'wrong' now -- they still represent a nomenclatural act which really happened.

Such names include:
- Currently accepted names
- Valid synonyms of any sort -- homotypic synonyms (old combinations), heterotypic synonyms (two names for what was found be one species), names describing taxon concept (sensu, sec. ... "Stenometope laevissimus sec. Eschmeyer 2004" )
- Names described after the fact (ex ... like "Osmundaria obtusiloba (Mertens ex C. Agardh) R.E. Norris" which means Agardh added a name to a collection item, and later Mertens described it properly, and later Norris created a new combination)

Such names do not include:
- Misspellings
- Chresonyms (names containing aurhors who had nothing to do with the corresponding nomenclatural act ... like "Monochamus galloprovincialis De Fluiter, 1950")
- Name not properly described and published

### 2. Names currently accepted by taxonomists (subjective)

Such names are currently accepted by all or some taxonomists to represent a taxon concept -- a group of organisms (living or  not) united by this name into a taxonomic clade.

Such names are subjective because they represent an opinion of taxonomists.
This group is a 'perfect' subset of names from the first group. It can only be formed from nomenclaturally valid names.

**Comment by dimus** [comment]
The 'right' way to deal with our task is to collect each and every nomenclatural act ever published and extract corresponding names from them. Solving our task this way would be definitive, but it would take a lot of work. We are taking a shortcut. Wencan is creating a classifier, trains it on good and bad names, and lets it sort names from Global Names database into 'good' and bad'. Then we take input from taxonomists, and improve algorithm asymptotically approaching an 'ideal' goal.

**Comment by dimus** [comment]
Paddy worked on my text and made corrections/suggestions
https://docs.google.com/document/d/1p76P62fuP_YA-aKu82BX4Tbi1qiqkcrEP0Kv33Nwpf0/edit#heading=h.sr7c4il1s50p
